[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "always"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "5000"

[healthcheck]
  path = "/api/health"
  timeout = 10
  interval = 30