[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
initialDelaySeconds = 30
timeoutSeconds = 10
intervalSeconds = 30
failureThreshold = 3

[environment]
NODE_ENV = "production"
PORT = "${{ PORT }}"